### ISSUE TITLE
[future] decouple from K8s API maybe :)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/windows-service-proxy#18]
There are two ways to do this proxy:

1. all in memory
2. using KPNGs GRPC data model, where the backends dont have k2s as functionality but rather, only run a standalone backend that recieves KPNG objects as inputs.

the latter has the advantage of totally deocupling us from k8s API , making it much more lightweight.

Theres (obvious) pros and cons to these approaches.

This issue tracks them, and allows us a place to debate them.

**Comment by marosset** [comment]
Do we have a plan for how to tell the backend where to connect to in order to get updates?
For a production clusters I image we'd want to run the KPNG component that watches the api-server as a K8s service for HA and if we do that we'd also need to potentially figure out how to program routes on the node so the KPNG backends can connect to the watcher. 
I'm certainly not opposed to decoupling the watcher and backend for Windows but we'd need to robust way to bootstrap everything first.

**Comment by jayunit100** [comment]
Folks are building dev tooling to make this repo easy to contribute to .... still relevant

**Comment by jayunit100** [comment]
Keep this going
